### ISSUE TITLE
Like feature can't be used

### ISSUE THREAD

**Issue by crimcrimreborn** [AdamBankz/tiktool#1]
Exception in thread Thread-1 (run_likes_bot):
Traceback (most recent call last):
  File "D:\Python\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "D:\Python\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tiktool-release\main.py", line 231, in run_likes_bot
    input.send_keys(self.entry2.get())
  File "D:\Python\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 303, in send_keys
    self._execute(
  File "D:\Python\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "D:\Python\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=135.0.7049.96)
Stacktrace:
        GetHandleVerifier [0x00BC8073+60707]
        GetHandleVerifier [0x00BC80B4+60772]
        (No symbol) [0x009F04FE]
        (No symbol) [0x00A33069]
        (No symbol) [0x00A31706]
        (No symbol) [0x00A5D04C]
        (No symbol) [0x00A2DCA4]
        (No symbol) [0x00A5D2C4]
        (No symbol) [0x00A7E824]
        (No symbol) [0x00A5CE46]
        (No symbol) [0x00A2C5D3]
        (No symbol) [0x00A2D424]
        GetHandleVerifier [0x00E0BB53+2435075]
        GetHandleVerifier [0x00E070F3+2416035]
        GetHandleVerifier [0x00E2349C+2531660]
        GetHandleVerifier [0x00BDF145+155125]
        GetHandleVerifier [0x00BE5AED+182173]
        GetHandleVerifier [0x00BCF948+91640]
        GetHandleVerifier [0x00BCFAF0+92064]
        GetHandleVerifier [0x00BBA5B0+4704]
        BaseThreadInitThunk [0x76F3FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x778F82AE+286]
        RtlGetAppContainerNamedObjectPath [0x778F827E+238]

**Comment by AdamBankz** [comment]
Zefoy changed their website structure. I've pushed the fixed code to github. 

Reinstall the repository as a ZIP and run the new main.py.
Likes and views should work, followers are down until zefoy updates it.

**Comment by jaspex5x** [comment]
likes don't work just tells me this and redownloaded like told and didn't fix the issue
GetHandleVerifier [0x00BC8073+60707]
GetHandleVerifier [0x00BC80B4+60772]
(No symbol) [0x009F04FE]
(No symbol) [0x00A33069]
(No symbol) [0x00A31706]
(No symbol) [0x00A5D04C]
(No symbol) [0x00A2DCA4]
(No symbol) [0x00A5D2C4]
(No symbol) [0x00A7E824]
(No symbol) [0x00A5CE46]
(No symbol) [0x00A2C5D3]
(No symbol) [0x00A2D424]
GetHandleVerifier [0x00E0BB53+2435075]
GetHandleVerifier [0x00E070F3+2416035]
GetHandleVerifier [0x00E2349C+2531660]
GetHandleVerifier [0x00BDF145+155125]
GetHandleVerifier [0x00BE5AED+182173]
GetHandleVerifier [0x00BCF948+91640]
GetHandleVerifier [0x00BCFAF0+92064]
GetHandleVerifier [0x00BBA5B0+4704]
BaseThreadInitThunk [0x76F3FCC9+25]
RtlGetAppContainerNamedObjectPath [0x778F82AE+286]
RtlGetAppContainerNamedObjectPath [0x778F827E+238]
just tells me this and redownloaded like told and didn't fix the issue

**Comment by AdamBankz** [comment]
Retry now.
